server:
  port: 9101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka
spring:
  zipkin:
    base-url: http://localhost:9411
  #spring.sleuth.sampler.percentage=1，则每次的信息都进入了zipkin
  sleuth:
    sampler:
      percentage: 1