server:
  port: 8881
spring:
  application:
    name: eureka2
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
    prefer-ip-address: true
    # 每间隔5s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 5
    # 告诉服务端，如果我10s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 16
  client:
    #从Eureka服务端获取注册信息的时间间隔
    registryFetchIntervalSeconds: 1
    #更新实例信息变化到Eureka服务端的间隔时间
    instanceInfoReplicationIntervalSeconds: 1
    #是否注册到Eureka中
    registerWithEureka: true
    #是否需要去检索寻找服务，默认是true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8880/eureka/