server:
  port: 8895
spring:
  application:
    name: consumer
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    #是否注册到Eureka中
    registerWithEureka: true
    #是否需要去检索寻找服务，默认是true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8880/eureka/,http://${eureka.instance.hostname}:8881/eureka/